export const PLANS = {
  FREE: {
    name: 'Free',
    priceMonthly: 0,
    priceYearly: 0,
    maxSites: 1,
    maxPages: 1,
    maxWaitlistEntries: 100,
    maxPaymentLinks: 0,
    maxStorageMb: 50,
    templates: false,
    waitlist: true,
    referralSystem: false,
    customDomain: false,
    removeBranding: false,
    googleSheets: false,
    webhooks: false,
    analytics: false,
    abTesting: false,
  },
  LITE: {
    name: 'Lite',
    priceMonthly: 100,
    priceYearly: 1000,
    maxSites: 1,
    maxPages: 3,
    maxWaitlistEntries: 999999,
    maxPaymentLinks: 3,
    maxStorageMb: 100,
    templates: true,
    waitlist: true,
    referralSystem: true,
    customDomain: true,
    removeBranding: true,
    googleSheets: true,
    webhooks: true,
    analytics: true,
    abTesting: false,
  },
  STARTER: {
    name: 'Starter',
    priceMonthly: 500,
    priceYearly: 5000,
    maxSites: 1,
    maxPages: 5,
    maxWaitlistEntries: 999999,
    maxPaymentLinks: 3,
    maxStorageMb: 200,
    templates: true,
    waitlist: true,
    referralSystem: true,
    customDomain: true,
    removeBranding: true,
    googleSheets: true,
    webhooks: true,
    analytics: true,
    abTesting: false,
  },
  PRO: {
    name: 'Pro',
    priceMonthly: 900,
    priceYearly: 9000,
    maxSites: 5,
    maxPages: 10,
    maxWaitlistEntries: 999999,
    maxPaymentLinks: 5,
    maxStorageMb: 500,
    templates: true,
    waitlist: true,
    referralSystem: true,
    customDomain: true,
    removeBranding: true,
    googleSheets: true,
    webhooks: true,
    analytics: true,
    abTesting: false,
  },
  BUSINESS: {
    name: 'Business',
    priceMonthly: 2900,
    priceYearly: 29000,
    maxSites: 999999,
    maxPages: 999999,
    maxWaitlistEntries: 999999,
    maxPaymentLinks: 999999,
    maxStorageMb: 5000,
    templates: true,
    waitlist: true,
    referralSystem: true,
    customDomain: true,
    removeBranding: true,
    googleSheets: true,
    webhooks: true,
    analytics: true,
    abTesting: true,
  },
} as const;

export type PlanTier = keyof typeof PLANS;
export type PlanConfig = (typeof PLANS)[PlanTier];

export const LIMITS = {
  SLUG_MIN_LENGTH: 3,
  SLUG_MAX_LENGTH: 50,
  SITE_NAME_MAX_LENGTH: 100,
  WAITLIST_EMAIL_MAX_LENGTH: 255,
  CHANGELOG_TITLE_MAX_LENGTH: 200,
  CHANGELOG_BODY_MAX_LENGTH: 10_000,
  AB_TEST_MAX_VARIANTS: 5,
} as const;
